#!/bin/bash

# Update package index
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Backup the default HAProxy configuration
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Create a new HAProxy configuration file
sudo touch /etc/haproxy/haproxy.cfg

# Write the HAProxy configuration
sudo cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 34.232.71.73-web-01:80 check
    server web-02 100.26.155.79-web-02:80 check
EOF

# Verify the configuration syntax
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart HAProxy service
sudo systemctl restart haproxy

# Enable HAProxy service to start on boot
sudo systemctl enable haproxy

# Verify HAProxy status
sudo systemctl status haproxy

