#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Update package index
apt-get -y update

# Install HAproxy
apt-get -y install haproxy

# Overwrite haproxy configuration file with new configuration
cat <<EOF > /etc/haproxy/haproxy.cfg
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend sammykingx.tech
    bind 0:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 64820-web-01 34.232.71.73-web-01:80 check
    server 64820-web-02 100.26.155.79-web-02:80 check
EOF

# Restart HAproxy service
systemctl restart haproxy

